### ISSUE TITLE
all requests get 401 "auth token expired" after a while

### ISSUE THREAD

**Issue by vitriolix** [vitalif/grive2#19]
I am trying to sync some large photo backup folders, 20GB in total, a few thousand files. After grive 2 runs for a certain amount of time, probably more than an hour, all requests are getting "auth token expired".  If I restart it picks up where it ran into trouble before for another hour, then hits the same thing again at a new point.

```
request failed due to auth token expired: 401 (body: {
 "error": {
  "errors": [
   {
    "domain": "global",
    "reason": "authError",
    "message": "Invalid Credentials",
    "locationType": "header",
    "location": "Authorization"
   }
  ],
  "code": 401,
  "message": "Invalid Credentials"
 }
}
). refreshing token
```

**Comment by TimKrause2** [comment]
That's the exact same thing happening to me.

**Comment by mafe** [comment]
Same here:
```
sync "/home/xf/syncfolder/Encoded/qKsrfXa3i/VU4H,IPvmjL-NQnObwaFdQDYdA0-tusy6dVLvlOwo7AVy/HYRG,dPET31MI1uYzczoLZE,/O2AxiLeLXmA0Hvzc2hyj
,TRn" doesn't exist in server, uploading
HTTP POST "https://www.googleapis.com/drive/v2/files" with "{"parents":[{"id":"0B5yFkrNfdsfWllJdUtGeG1NT2c"}],"title":"O2AxiLeLXmAba0Hvzc2hyj,TRn"}"
HTTP response 401
resquest failed due to auth token expired: 401. refreshing token
HTTP POST "https://www.googleapis.com/drive/v2/files" with "{"parents":[{"id":"0B5yFkrNyHBi1WllJdUtGeE1NT2c"}],"title":"O2AxiLeLXmAba0Hvzc2hyj,TRn"}"
exception: /home/mf/!src/!makepkg/grive2/src/Grive2-0.3/libgrive/src/json/JsonParser.cc(169): Throw in function void gr::JsonParser::Parse(const char*,
 std::size_t)
Dynamic exception type: boost::exception_detail::clone_impl<gr::JsonParser::Error>
[gr::expt::BacktraceTag*] = #0 0x4840fc grive2 gr::Exception::Exception()
#1 0x46b281 grive2 gr::JsonParser::Error::Error()
#2 0x46a440 grive2 gr::JsonParser::Parse(char const*, unsigned long)
#3 0x47badd grive2 gr::http::ValResponse::Write(char const*, unsigned long)
#4 0x7f16b6402c02 /usr/lib/libcurl.so.4 
#5 0x7f16b641e3e0 /usr/lib/libcurl.so.4 
#6 0x7f16b6418c47 /usr/lib/libcurl.so.4 
#7 0x7f16b6422c72 /usr/lib/libcurl.so.4 
#8 0x7f16b6423a9d /usr/lib/libcurl.so.4 curl_multi_perform
#9 0x7f16b641a6cb /usr/lib/libcurl.so.4 curl_easy_perform
#10 0x45f3e3 grive2 gr::http::CurlAgent::ExecCurl(std::string const&, gr::DataStream*, gr::http::Header const&)
#11 0x460156 grive2 gr::http::CurlAgent::Post(std::string const&, std::string const&, gr::DataStream*, gr::http::Header const&)
#12 0x46570c grive2 gr::AuthAgent::Post(std::string const&, std::string const&, gr::DataStream*, gr::http::Header const&)
#13 0x45caad grive2 gr::v2::Syncer2::Upload(gr::Resource*)
#14 0x45e84b grive2 gr::v2::Syncer2::Create(gr::Resource*)
#15 0x454be7 grive2 gr::Resource::SyncSelf(gr::Syncer*, gr::Val const&)
#16 0x45545e grive2 gr::Resource::Sync(gr::Syncer*, gr::DateTime&, gr::Val const&)
#17 0x4555dc grive2 gr::Resource::Sync(gr::Syncer*, gr::DateTime&, gr::Val const&)
#18 0x4555dc grive2 gr::Resource::Sync(gr::Syncer*, gr::DateTime&, gr::Val const&)
#19 0x4555dc grive2 gr::Resource::Sync(gr::Syncer*, gr::DateTime&, gr::Val const&)
#20 0x4555dc grive2 gr::Resource::Sync(gr::Syncer*, gr::DateTime&, gr::Val const&)
#21 0x4555dc grive2 gr::Resource::Sync(gr::Syncer*, gr::DateTime&, gr::Val const&)
#22 0x4555dc grive2 gr::Resource::Sync(gr::Syncer*, gr::DateTime&, gr::Val const&)
#23 0x458a78 grive2 gr::State::Sync(gr::Syncer*, gr::Val const&)
#24 0x44d596 grive2 gr::Drive::Update()
#25 0x43f9ae grive2 Main(int, char**)
#26 0x43cb9b grive2 main
#27 0x7f16b45cf790 /usr/lib/libc.so.6 __libc_start_main
#28 0x43d859 grive2 _start

[gr::JsonText*] = {
 "kind": "drive#file",
 "id": "0B5yFkrNyHBi1cGtDSkE4X2RsU0U",
 "etag": "\"9Atp-NBBQmHtE7w2vMGY_7-2FUk/MTQEODcxNDY2NzgwNQ\"",
 "selfLink": "https://www.googleapis.com/drive/v2/files/0B5yFkrNyHBi1cGtDSkE4X2RsU0U",
 "webContentLink": "https://docs.google.com/uc?id=0B5yFkrNffBi1cGtDSkE4X2RsU0U&export=download",
 "alternateLink": "https://drive.google.com/file/d/0B5yFkrNffBi1cGtDSkE4X2RsU0U/view?usp=drivesdk",
 "iconLink": "https://ssl.gstatic.com/docs/doclist/images/icon_10_generic_list.png",
 "title": "O2AxiLeLXmA0Hv2c2hyj,TRn",
 "mimeType": "application/octet-stream",
 "labels": {
  "starred": false,
  "hidden": false,
  "trashed": false,
  "restricted": false,
  "viewed": true
 },
 "createdDate": "2015-08-04T18:57:47.887Z",
 "modifiedDate": "2015-08-04T18:57:47.805Z",
 "modifiedByMeDate": "2015-08-04T18:57:47.805Z",
 "lastViewedByMeDate": "2015-08-04T18:57:47.805Z",
 "markedViewedByMeDate": 
[gr::ParseErr*] = parse error: trailing garbage
                                       {  "kind": "drive#file",  "id":
                     (right here) ------^

```

**Comment by vitalif** [comment]
@mafe it's not the same bug, it seems it's the one already fixed in master (the one with AuthAgent reusing same response on errors)

**Comment by vitalif** [comment]
Just fixed it - the problem was AuthAgent not appending the refreshed token into http headers on retry in Put() method.

**Comment by vitriolix** [comment]
I'm not getting this error anymore.  Thanks.

I'm not sure its related so I opened a new issue, but now I'm getting a ton of "Precondition failed" errors:

https://github.com/vitalif/grive2/issues/21

**Comment by cinquecento** [comment]
The issue is still actual
```
$ grive --verbose
...
sync "./.../Fedora-Xfce-Live-0907.iso" doesn't exist in server, uploading
  [100%] [=================================================>] 1.19/1.19GB
...
request failed due to auth token expired: 401 (body: {
 "error": {
  "errors": [
   {
    "domain": "global",
    "reason": "authError",
    "message": "Invalid Credentials",
    "locationType": "header",
    "location": "Authorization"
   }
  ],
  "code": 401,
  "message": "Invalid Credentials"
 }
}
). refreshing token
...

$ grive --version
grive version 0.5.1-dev Sep  6 2016 21:18:20
```
In fact, the issue tends to cause transfer breakage.

**Comment by cinquecento** [comment]
See https://github.com/vitalif/grive2/issues/107
